# Lista

## Ordenar Listas

sort() es un método en Python que se utiliza para ordenar elementos en una lista de forma ascendente por defecto, o de acuerdo a una función de comparación personalizada.

In [ ]:
edades=[95,38,15,75,25,56,14,7,5,53]

In [ ]:
edades.sort() #Por defecto orden ascendente - reverse=False

edades

Ahora queremos ordenar de forma descendent

In [ ]:
edades.sort(reverse=True)

edades

sorted() es una función en Python que se utiliza para ordenar elementos en una lista y devolver una nueva lista ordenada sin modificar la lista original. A diferencia del método sort() que ordena la lista in situ, sorted() devuelve una nueva lista ordenada, dejando la lista original intacta.

In [ ]:
edades_ascendente = sorted(edades)

edades_ascendente

Tambien podemos ordenar tuplas

In [ ]:
estudiantes=("Beto", "Carlos", "Ana")

estud_ordenados= sorted(estudiantes)

estud_ordenados

Búsqueda a través del índice de los elementos de una lista o una tupla.

In [ ]:
edad = [65, 12, 19, 80, 36, 28, 16, 18, 36, 16, 45, 32, 36, 59]
edad.index(45)


In [ ]:
edad.index(43)

Verificar si algún valor está en la lista es con el comando in

In [ ]:
56 in edad

Insertar elemenos en una lista - Funcion insert()

In [ ]:
vegetales = ["Espinaca","Apio"]
vegetales.insert(0,"Lechuga")
vegetales

Para agregar al final de la lista - Funcion append

In [ ]:
vegetales.append("Esparrago")
vegetales

Para agregar mas elementos - Comando extend()

In [ ]:
precio=(10,15,8,30)

vegetales.extend(precio)

vegetales

#Equivalente a concatenar dos listas

Dejamos vacia la Lista

In [ ]:
vegetales.clear()
vegetales

Contamos la cantidad de veces que aparecen elementos dentro de una lista

In [ ]:
edades = [15, 21, 16, 19, 20, 16, 19, 15, 21, 17, 18, 24, 20, 24, 21, 19, 18, 16, 19, 16]
for edad in range(15, 25):
    print(f'La edad {edad} se repite {edades.count(edad)} veces')


Copiamos una lista

In [ ]:
vegetales=['Lechuga', 'Espinaca', 'Apio', 'Esparrago', 'Esparrago']
vegetales

In [ ]:
copia_vegetales = vegetales.copy()

copia_vegetales

# Listas Multidimensionales

In [ ]:
# Matriz de calificaciones
calificaciones = [
    [85, 90, 88],  # Matemáticas
    [78, 8, 80],  # Ciencias
    [92, 88, 95]   # Historia
]

# Imprimir la matriz completa
print("Matriz de Calificaciones:")
for fila in calificaciones:
    print(fila)


Matriz de Calificaciones:
[85, 90, 88]
[78, 8, 80]
[92, 88, 95]


In [ ]:
# Acceder a una calificación específica
calificacion_ciencias_2 = calificaciones[1][1]
print("La segunda calificación en Ciencias es:", calificacion_ciencias_2)


La segunda calificación en Ciencias es: 8


In [ ]:
# Modificar una calificación
calificaciones[2][1] = 90  # Cambiar la segunda calificación en Historia a 90
print("Matriz de Calificaciones después de la modificación:")
for fila in calificaciones:
    print(fila)


In [ ]:
# Calcular el promedio de calificaciones por materia
promedios = []
for fila in calificaciones:
    promedio = sum(fila) / len(fila)
    promedios.append(promedio)

print("Promedios de Calificaciones por Materia:", promedios)

# Diccionario

Vamos  a crear un diccionario con los nombres Laura, Daniel, Alberto y Rogelio, y sus códigos la, dn, al, ro.

In [ ]:
nombre_usuario={"Laura":"la","Daniel":"da","Alberto":"al","Rogelio":"ro"}

In [ ]:
nombre_usuario

¿Cuantas parejas hay en el diccionario?

In [ ]:
len(nombre_usuario)

Ahora crea un diccionario donde mapees a los usuarios con su edad - 28, 31, 27 y 65 respectivamente.

In [ ]:
edad_usuario={"Laura":28,"Daniel":31,"Alberto":27,"Rogelio":65}

edad_usuario

{'Laura': 28, 'Daniel': 31, 'Alberto': 27, 'Rogelio': 65}

Arma un programa que nos diga en forma de oración **"X tiene Y años"** para cada uno de los 4 participantes. (Ej - Laura tiene 28 años cumplidos)

In [ ]:
for usuario,edad in edad_usuario.items():
  print(usuario,"tiene",edad,"años cumplidos")

Laura tiene 28 años cumplidos
Daniel tiene 31 años cumplidos
Alberto tiene 27 años cumplidos
Rogelio tiene 65 años cumplidos


## Operaciones Básicas (como acceder, modificarlos y borrarlos)

Accede a 2 Usuarios

In [ ]:
edad_usuario

In [ ]:
edad_usuario["Laura"]

In [ ]:
edad_usuario[]

In [ ]:
edad_usuario[31]

Cambia el valor de alguan de las llaves - Resulta que Rogelio en realidad tiene 35 años

In [ ]:
edad_usuario["Rogelio"]=35

In [ ]:
edad_usuario

Se integra un nuevo elemento - Eva de 29 años, agregala al diccionario

In [ ]:
edad_usuario["Eva"]=29

In [ ]:
edad_usuario

Daniel decidió que no somos lo suficientemente bueno - borralo


In [ ]:
del edad_usuario["Daniel"]

In [ ]:
edad_usuario

Buscamos a Daiel ahora en el Diccionario

In [ ]:
edad_usuario["Daniel"]

Ahora usa Get para conocer la edad de Daniel y evitar un error

In [ ]:
edad_usuario.get("Daniel","No esta en el diccionario")

Prueba si Daniel y Eva están en el diccionario

In [ ]:
"Daniel" in edad_usuario

True

In [ ]:
"Eva" in edad_usuario

## Metodos de Diccionario

Anteriormente, usamos el método items para iterar a través de las tuplas de un key-value pair. Asimismo, lo métodos keys y values pueden susares para iterar las llaves y valores de un diccionario.

edad_usuario={"Laura":28,"Daniel":31,"Alberto":27,"Rogelio":65}

In [ ]:
edad_usuario={"Laura":28,"Daniel":31,"Alberto":27,"Rogelio":65}

edad_usuario

Arma un for que muestre los nombres de los participantes - sacados de usuario_edad

In [ ]:
for usuario in edad_usuario.keys():
  print(usuario, end=", ")

Laura, Daniel, Alberto, Rogelio, 

In [ ]:
for usuario in edad_usuario.values():
  print(usuario, end=", ")

  #LO CORRI PARA VER SI ESTO DEL NOMBRE USUARIO ERA EL MISMOQ UE DEFINI ANTES, APARENTEMENTE NO, SOLAMENTE ANTES HABIA SIDO UNA VARIABLE "NO GLOBAL" ? SOLO PARA ESA PARTE DE LA FUNCION,
  #AHORA PODIA USAR DE NOMBRE VARIABEL CUALQUIER COSA


28, 31, 27, 65, 

In [ ]:
for cualquier_cosa in edad_usuario.values():
  print(cualquier_cosa, end=", ")

#si pongo keys, me devuelve lo que va antes del ":"
# si pongo values, me devuelve lo que va despues del ":"

28, 31, 27, 65, 

Arma un for que muestre las edades de los participantes

In [ ]:
for edad in edad_usuario.values():
  print(edad, end=", ")

28, 31, 27, 65, 

A veces es necesario trabajar con las llaves y valores del diccionario - Eso lo logramos convirtiendo nuestras llaves y valores en listas con la función list

In [ ]:
list(edad_usuario.items())

[('Laura', 28), ('Daniel', 31), ('Alberto', 27), ('Rogelio', 65)]

Para ordenar en orden alfabético las llaves del diccionario

In [ ]:
for nombre in sorted(edad_usuario.keys()):
  print(nombre, end=", ")

Alberto, Daniel, Laura, Rogelio, 

In [ ]:
edad_usuario

{'Laura': 28, 'Daniel': 31, 'Alberto': 27, 'Rogelio': 65}

# Comprensión de Diccionarios

Python te permite comparar diccionarios .

Compara estos 3:

In [ ]:
asistentes_dia1={'Ramírez':'Laura','Cortés': 'Daniel','Pérez':'Alberto'}

asistentes_dia2={'García':'Rogelio','Ramírez': 'Laura','Pérez':'Alberto'}

asistentes_dia3={'Pérez':'Alberto','Cortés': 'Daniel','Ramírez':'Laura'}

In [ ]:
asistentes_dia1 == asistentes_dia2

False

In [ ]:
asistentes_dia1 == asistentes_dia3

True

# Arreglos con NUMPY

NumPy es una de las librerías más populares de Python, ya que puede procesar listas de múltiples dimensiones

## Arreglo de Datos

Invocamos a la librería NumPy como np

In [ ]:
import numpy as np


Armemos un arreglo de todos los factoriales del 1 al 6

In [ ]:
factorial = np.array([1,2,6,24,120,720])

factorial

Verifica el tipo de objeto que generamos

In [ ]:
type(factorial)

La función array copia automáticamente las dimensiones del argumento. Por ejemplo, el siguiente arreglo (array) está formado por tres filas y dos columnas.

In [ ]:
np.array([[3,4],[6,7],[10,11]])

## Atributos del Arreglo

Se puede iterar facilmente a través de un arreglo

In [ ]:
flotantes = np.array([[9 ** (1/2), 10 ** (1/2), 3.33], [10 / 3, 3.4, 3.03]])

flotantes

array([[3.        , 3.16227766, 3.33      ],
       [3.33333333, 3.4       , 3.03      ]])

In [ ]:
for fila in flotantes:
    for columna in fila:
        print(columna, end=' ')
    print()

## Creando Arreglos desde Rangos

La función arange (una sola R!!!!) nos permite crear rangos de enteros. Crea:

- Un arreglo del 0 al 7
- Un arreglo del 3 al 7
- Un arreglo del 12 al 2 en pasos de 3 en 3 (si, en orden inverso)

In [ ]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.arange(3,8)

array([3, 4, 5, 6, 7])

In [ ]:
np.arange(12,2,-3)

array([12,  9,  6,  3])

Tambien se pueden usar tamaños de paso no enteros. Crea un arreglo con linspace de 0 al 1 que vaya de .25 en .25

In [ ]:
np.linspace(0,1,num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Y se puede cambiar la forma del arreglo con reshape. Crea un arreglo con arange que vaya del 21 al 1 en orden inverso, y luego dale forma de matriz de 4x5

In [ ]:
np.arange(21,1,-1).reshape(4,5)

array([[21, 20, 19, 18, 17],
       [16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2]])

si el arreglo tiene 1000 o más elementos, numpy no muestra la totalidad de los datos. Generaun arreglo de 0 a 9999 y dale forma de 5 x 2000

In [ ]:
np.arange(0,10000).reshape(5,2000)

array([[   0,    1,    2, ..., 1997, 1998, 1999],
       [2000, 2001, 2002, ..., 3997, 3998, 3999],
       [4000, 4001, 4002, ..., 5997, 5998, 5999],
       [6000, 6001, 6002, ..., 7997, 7998, 7999],
       [8000, 8001, 8002, ..., 9997, 9998, 9999]])

## Operaciones con Arreglos

Arma un arreglo de todos los pares del 2 al 15.

- Sumale 1 al arreglo
- Multiplicalo por 3
- Sacale raiz cuadrada

In [ ]:
lista1=np.arange(2,16,2)

lista1

In [ ]:
lista1+1

In [ ]:
lista1*3

In [ ]:
lista1**(1/2)

In [ ]:
lista1

Al mismo arreglo, aplicale un +=10

In [ ]:
lista1+=10

In [ ]:
lista1

Arma un arreglo (lista1) que vaya del 2 al 18 de 3 en 3, y otro arreglo (lista2) usando linspace que vaya del -2 al 20 dividido en 6 numeros

- Resta lista1 de lista2
- Divide lista2 entre lista1

In [ ]:
lista1=np.arange(2,18,3)
lista1

In [ ]:
lista2=np.linspace(-2,20,num=6)
lista2

In [ ]:
lista2 - lista1

In [ ]:
lista2 / lista1

# APIs

## API CLIMA - Open Weather

In [8]:
# Importamos la biblioteca requests
import requests

# Definimos una función para obtener el clima
def get_weather(api_key, city):
    base_url = "http://api.openweathermap.org/data/2.5/weather"
    params = {
        'q': city,
        'appid': api_key,
        'units': 'metric',  # para obtener la temperatura en grados Celsius
        'lang': 'es'        # idioma español
    }
    response = requests.get(base_url, params=params)
    return response.json()

# Tu API key (reemplaza 'your_api_key_here' con tu API key real) #https://home.openweathermap.org/api_keys
api_key = "f274978bf93696b3ab7e21b9c187bba5"

# La ciudad para la que quieres obtener el clima   # ej: Sierra de la Ventana o Buenos Aires https://openweathermap.org/weathermap?basemap=map&cities=true&layer=temperature&lat=-38.1497&lon=-61.6924&zoom=10
city = input("Ingrese el nombre de la ciudad: ")

# Obtenemos el clima
weather_data = get_weather(api_key, city)

# Mostramos los datos del clima
print(weather_data)

# Si quieres mostrar la información de una manera más amigable:
if weather_data.get('cod') == 200:
    main = weather_data['main']
    wind = weather_data['wind']
    weather_description = weather_data['weather'][0]['description']

    print(f"Ciudad: {city}")
    print(f"Temperatura: {main['temp']}°C")
    print(f"Humedad: {main['humidity']}%")
    print(f"Presión: {main['pressure']} hPa")
    print(f"Descripción del clima: {weather_description}")
    print(f"Velocidad del viento: {wind['speed']} m/s")
else:
    print("¡Ciudad no encontrada!")


Ingrese el nombre de la ciudad: Sierra de la Ventana
{'coord': {'lon': -61.7952, 'lat': -38.1381}, 'weather': [{'id': 804, 'main': 'Clouds', 'description': 'nubes', 'icon': '04d'}], 'base': 'stations', 'main': {'temp': 4.47, 'feels_like': 0.89, 'temp_min': 4.47, 'temp_max': 5.59, 'pressure': 1023, 'humidity': 51, 'sea_level': 1023, 'grnd_level': 977}, 'visibility': 10000, 'wind': {'speed': 4.57, 'deg': 243, 'gust': 7.04}, 'clouds': {'all': 99}, 'dt': 1719692727, 'sys': {'type': 2, 'id': 2030053, 'country': 'AR', 'sunrise': 1719660264, 'sunset': 1719694610}, 'timezone': -10800, 'id': 3835300, 'name': 'Sierra de la Ventana', 'cod': 200}
Ciudad: Sierra de la Ventana
Temperatura: 4.47°C
Humedad: 51%
Presión: 1023 hPa
Descripción del clima: nubes
Velocidad del viento: 4.57 m/s


## API - Star Wars

In [ ]:
# Instalamos la biblioteca requests
!pip install requests

# Importamos la biblioteca requests
import requests

# Definimos una función para obtener información sobre un personaje de Star Wars
def get_star_wars_character(character_id):
    base_url = f"https://swapi.dev/api/people/{character_id}/"
    response = requests.get(base_url)
    return response.json()

# ID del personaje (por ejemplo, Luke Skywalker tiene el ID 1)
character_id = 20

# Obtenemos la información del personaje
character_data = get_star_wars_character(character_id)

# Mostramos los datos del personaje
print(character_data)

# Si quieres mostrar la información de una manera más amigable:
print("\nInformación del personaje:")
print(f"Nombre: {character_data['name']}")
print(f"Altura: {character_data['height']} cm")
print(f"Peso: {character_data['mass']} kg")
print(f"Color de cabello: {character_data['hair_color']}")
print(f"Color de piel: {character_data['skin_color']}")
print(f"Color de ojos: {character_data['eye_color']}")
print(f"Año de nacimiento: {character_data['birth_year']}")
print(f"Género: {character_data['gender']}")
