# Introducción a NumPy

[Numpy](https://numpy.org) es una librería fundamental para la computación científica con Python.
* Proporciona arrays N-dimensionales
* Implementa funciones matemáticas sofisticadas
* Proporciona herramientas para integrar C/C++ y Fortran
* Proporciona mecanismos para facilitar la realización de tareas relacionadas con álgebra lineal o números aleatorios

## Imports

In [ ]:
# Instalación de Numpy y Matplotlib
!pip install numpy
!pip install matplotlib

In [ ]:
import numpy as np

## Arrays

Un **array** es una estructura de datos que consiste en una colección de elementos (valores o variables), cada uno identificado por al menos un índice o clave. Un array se almacena de modo que la posición de cada elemento se pueda calcular a partir de su tupla de índice mediante una fórmula matemática. El tipo más simple de array es un array lineal, también llamado array unidimensional.

En numpy:
* Cada dimensión se denomina **axis**
* El número de dimensiones se denomina **rank**
* La lista de dimensiones con su correspondiente longitud se denomina **shape**
* El número total de elementos (multiplicación de la longitud de las dimensiones) se denomina **size**

In [ ]:
# Array cuyos valores son todos 0
a = np.zeros((2, 4))

In [ ]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

_**a**_ es un array:
* Con dos **axis**, el primero de longitud 2 y el segundo de longitud 4
* Con un **rank** igual a 2
* Con un **shape** igual (2, 4)
* Con un **size** igual a 8

In [ ]:
a.shape

(2, 4)

In [ ]:
a.ndim

2

In [ ]:
a.size

8

## Creación de Arrays

In [ ]:
# Array cuyos valores son todos 0
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
# Array cuyos valores son todos 1
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
# Array cuyos valores son todos el valor indicado como segundo parámetro de la función
np.full((2, 3, 4), 8)

array([[[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]],

       [[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]]])

In [ ]:
# El resultado de np.empty no es predecible
# Inicializa los valores del array con lo que haya en memoria en ese momento
np.empty((2, 3, 9))

array([[[4.87362043e-310, 0.00000000e+000, 3.60330943e+252,
         1.62691065e+219, 2.02697730e+267, 2.64510886e+185,
         2.05932715e-115, 1.66036913e+243, 9.13551490e+242],
        [3.55455374e+180, 3.99523941e+252, 4.44386292e+252,
         6.38173991e+247, 3.96689508e+252, 4.37379127e+156,
         3.99523941e+252, 7.93260723e+223, 6.01346953e-154],
        [1.97249693e-153, 2.19980336e-152, 2.19980341e-152,
         1.66043032e+243, 1.23755836e+214, 7.71454051e+199,
         1.49708807e+248, 2.02697730e+267, 2.54828181e+161]],

       [[4.24976382e+175, 2.46345036e-154, 1.23159012e+171,
         1.02713581e+248, 3.68015657e+180, 1.52664645e-094,
         2.46929399e-027, 1.06112095e-153, 3.94560331e+180],
        [2.20892684e+161, 3.52337924e+246, 5.94764986e+228,
         9.05280232e+223, 2.14715295e+243, 2.97338839e-027,
         1.06209538e+248, 5.98178835e-154, 3.54582485e+246],
        [1.51327986e+256, 8.88755761e+247, 2.18174372e+243,
         3.94655056e+180, 8.90121

In [ ]:
# Inicializacion del array utilizando un array de Python
b = np.array([[1, 2, 3, 7], [4, 5, 6, 9]])
b

array([[1, 2, 3, 7],
       [4, 5, 6, 9]])

In [18]:
b.shape

(2, 4)

In [19]:
b.ndim

2

In [20]:
# Creación del array utilizando una función basada en rangos
# (minimo, maximo, número elementos del array)
np.linspace(0, 6, 10)

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [21]:
# Inicialización del array con valores aleatorios
np.random.rand(2, 3, 4)

array([[[0.88776638, 0.84107113, 0.26063773, 0.58481463],
        [0.3548962 , 0.59913745, 0.13634205, 0.81373205],
        [0.74650533, 0.30817844, 0.75426035, 0.59927992]],

       [[0.23681118, 0.0528852 , 0.69649685, 0.11713265],
        [0.81799625, 0.46282278, 0.31815883, 0.39777868],
        [0.784973  , 0.66856649, 0.63782266, 0.83710775]]])

In [22]:
# Inicialización del array con valores aleatorios conforme a una distribución normal
np.random.randn(2, 4)

array([[-2.19701895, -0.39399405,  2.2293729 ,  1.17736042],
       [ 0.80050889, -0.89773524,  2.46782281,  0.01036955]])

In [ ]:
%matplotlib inline #SOLO DE JUPYTER , ACA NO HACE FALTA
import matplotlib.pyplot as plt


c = np.random.randn(1000000) #DIBUJO UN MILLON DE NUMEROS ALEATORIOS Y QUE SE DISTRIBUYAN COMO UNA NORMAL ESTANDAR


#HARE UN HISTOGRAMA DE ESA DISTRIBUCION, CON 200 BINS (BARRAS DE RANGOS)
plt.hist(c, bins=200)
plt.show()

In [26]:
# Inicialización del Array utilizando una función personalizada

#FUNCION LLAMADA "fun", donde a partir de una funcion genero un array
def func(x, y):
    return x + 2 * y

np.fromfunction(func, (3, 5))

array([[ 0.,  2.,  4.,  6.,  8.],
       [ 1.,  3.,  5.,  7.,  9.],
       [ 2.,  4.,  6.,  8., 10.]])

## Acceso a los elementos de un array

### Array unidimensional

In [27]:
# Creación de un Array unidimensional
array_uni = np.array([1, 3, 5, 7, 9, 11])
print("Shape:", array_uni.shape)
print("Ndim:", array_uni.ndim)
print("Array_uni:", array_uni)
array_uni
type(array_uni)

Shape: (6,)
Ndim: 1
Array_uni: [ 1  3  5  7  9 11]


numpy.ndarray

In [28]:
array_uni
# como que cuando lo llamo solo aparece visualizado dintinto a que este dentro de un print

array([ 1,  3,  5,  7,  9, 11])

In [29]:
# Accediendo al quinto elemento del Array
array_uni[4]

9

In [33]:
# Accediendo al tercer y cuarto elemento del Array
array_uni[2:4]

array([5, 7])

In [34]:
#te da entre el primer y cuarto indice, el 5to no!!
array_uni[0:5]

array([1, 3, 5, 7, 9])

In [ ]:
# Accediendo a los elementos 0, 3 y 5 del Array (:: "final del array") (3--> "stride")
array_uni[0::3]

### Array multidimensional

In [35]:
# Creación de un Array multidimensional
array_multi = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Shape:", array_multi.shape)
print("Array_multi:\n", array_multi)
print("Ndim:", array_multi.ndim)
type(array_multi)
array_multi

Shape: (2, 4)
Array_multi:
 [[1 2 3 4]
 [5 6 7 8]]
Ndim: 2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
# Accediendo al cuarto elemento del Array ([indice_fila,indice_columna])
array_multi[0, 3]

4

In [37]:
# Accediendo a la segunda fila del Array
array_multi[1, :]

array([5, 6, 7, 8])

In [38]:
# Accediendo al tercer elemento de las dos primeras filas del Array
array_multi[0:2, 2]


array([3, 7])

In [ ]:
#Idem anterior
array_multi[:, 2]

## Modificación de un Array

In [41]:
# Creo un Array unidimensional inicializado con el rango de elementos 0-27
array1 = np.arange(28)

In [42]:
#  caracteristicas del array generado:
print("Shape:", array1.shape)
print("Ndim:", array1.ndim)
print("Array 1:", array1)

Shape: (28,)
Ndim: 1
Array 1: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]


In [46]:
# ahora a ese mismo array con esos mismos numeros le cambio las dimensiones del Array y sus longitudes (solamente se "reacomoda" en otra matriz.)
array1.shape = (7,4)
print("Shape:", array1.shape)
print("Ndim:", array1.ndim)
print("Array 1:\n", array1)

Shape: (7, 4)
Ndim: 2
Array 1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


 en este caso fue posible con 7,4 porque 7*4=28 posiciones, tiene que dar 28 (la cantidad original de posiciones)
la cuenta sino no se puede armar la matriz

In [48]:
# El ejemplo anterior devuelve un nuevo Array que apunta a los mismos datos.
# Importante: Modificaciones en un Array, modificaran el otro Array
array2 = array1.reshape(4, 7)
print("Shape:", array2.shape)
print("Array 2:\n", array2)

Shape: (4, 7)
Array 2:
 [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


In [52]:
# Modificación del nuevo Array devuelto
array2[0, 3] = 20000
print("Array 2:\n", array2)

Array 2:
 [[    0     1     2 20000     4     5     6]
 [    7     8     9    10    11    12    13]
 [   14    15    16    17    18    19    20]
 [   21    22    23    24    25    26    27]]


In [54]:
print("Array 1:\n", array1)
#esto demuestraa que aunque cree un array2 sobre la base del array1 y lo modifico al 1 para eso, entonces el 1 se va a ver modificado tambien!!!!!! ojo!!!

Array 1:
 [[    0     1     2 20000]
 [    4     5     6     7]
 [    8     9    10    11]
 [   12    13    14    15]
 [   16    17    18    19]
 [   20    21    22    23]
 [   24    25    26    27]]


In [ ]:
## Desenvuelve (ravel) el Array, devolviendo un nuevo Array de una sola dimension
# Importante: El nuevo array apunta a los mismos datos
print("Array 1:", array1.ravel())

## Operaciones aritméticas con Arrays

In [61]:
# Creación de dos Arrays unidimensionales
array1 = np.arange(2, 18, 2)
array2 = np.arange(8)
print("Array 1:", array1)
print("Array 2:", array2)

Array 1: [ 2  4  6  8 10 12 14 16]
Array 2: [0 1 2 3 4 5 6 7]


In [62]:
# Suma
print(array1 + array2)

[ 2  5  8 11 14 17 20 23]


In [63]:
# Resta
print(array1 - array2)

[2 3 4 5 6 7 8 9]


In [64]:
# Multiplicacion
# Importante: No es una multiplicación de matrices
print(array1 * array2)

[  0   4  12  24  40  60  84 112]


## Broadcasting

Si se aplican operaciones aritméticas sobre Arrays que no tienen la misma forma (shape) Numpy aplica un propiedad que se denomina Broadcasting.

In [ ]:
# Creación de dos Arrays unidimensionales
array1 = np.arange(5)
array2 = np.array([3])
print("Shape Array 1:", array1.shape)
print("Array 1:", array1)
print()
print("Shape Array 2:", array2.shape)
print("Array 2:", array2)

In [ ]:
# Suma de ambos Arrays
array1 + array2

In [ ]:
# Creación de dos Arrays multidimensional y unidimensional
array1 = np.arange(6)
array1.shape = (2, 3)
array2 = np.arange(6, 18, 4)
print("Shape Array 1:", array1.shape)
print("Array 1:\n", array1)
print()
print("Shape Array 2:", array2.shape)
print("Array 2:", array2)

In [ ]:
# Suma de ambos Arrays
array1 + array2

## Funciones estadísticas sobre Arrays

In [ ]:
# Creación de un Array unidimensional
array1 = np.arange(1, 20, 2)
print("Array 1:", array1)

In [ ]:
# Media de los elementos del Array
array1.mean()

In [ ]:
# Suma de los elementos del Array
array1.sum()

In [ ]:
help(array1.max)

In [ ]:
dir(array1)

Funciones universales eficientes proporcionadas por numpy: **ufunc**

In [ ]:
# Cuadrado de los elementos del Array
np.square(array1)

In [ ]:
# Raiz cuadrada de los elementos del Array
np.sqrt(array1)

In [ ]:
# Exponencial de los elementos del Array
np.exp(array1)

In [ ]:
# log de los elementos del Array
np.log(array1)